apiVersion: v1
kind: Service
metadata:
  name: react-currency-service
spec:
  type: NodePort
  selector:
    app: react-currency-converter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # Can be any port between 30000-32767
